import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./styles/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#fbe8e7",
        tertiary: "#904c24",
        "on-secondary-fixed": "#00201b",
        "on-secondary-container": "#007164",
        background: "#faf8ff",
        "on-surface": "#131b2e",
        primary: "#e11d48",
        "primary-fixed-dim": "#fecdd3",
        "on-surface-variant": "#564241",
        "surface-variant": "#fce7e7",
        "error-container": "#ffdad6",
        "inverse-surface": "#1e293b",
        "surface-container": "#fff1f2",
        "on-secondary-fixed-variant": "#005046",
        "inverse-primary": "#fda4af",
        "surface-tint": "#f43f5e",
        "on-tertiary-fixed-variant": "#72360e",
        "tertiary-container": "#df8d5f",
        "on-tertiary-fixed": "#331100",
        "primary-container": "#f87b7b",
        "secondary-fixed-dim": "#a7f3d0",
        "tertiary-fixed-dim": "#ffb68f",
        "secondary-container": "#ccfbf1",
        secondary: "#0d9488",
        surface: "#ffffff",
        "outline-variant": "#e2e8f0",
        "tertiary-fixed": "#ffdbca",
        error: "#ba1a1a",
        "surface-dim": "#f1f5f9",
        "on-primary-fixed": "#4c0519",
        "inverse-on-surface": "#f8fafc",
        "on-error-container": "#93000a",
        "surface-container-high": "#ffe4e6",
        "secondary-fixed": "#99f6e4",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-bright": "#ffffff",
        "primary-fixed": "#ffe4e6",
        "on-primary-fixed-variant": "#9f1239",
        "on-tertiary-container": "#5f2701",
        "on-tertiary": "#ffffff",
        "on-background": "#131b2e",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#ffffff",
        outline: "#8a7170",
        "on-error": "#ffffff",
        "surface-container-low": "#fff5f5",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "gutter-mobile": "1rem",
        "space-xl": "4rem",
        "margin-mobile": "1.25rem",
        gutter: "2rem",
        "space-lg": "2.5rem",
        margin: "4rem",
        "space-md": "1.5rem",
        "space-2xl": "6rem",
        "space-sm": "1rem",
        "space-xs": "0.5rem",
      },
      fontFamily: {
        "headline-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta)", "sans-serif"],
        "label-eyebrow": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-sm": ["var(--font-plus-jakarta)", "sans-serif"],
        "label-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-xl-mobile": ["var(--font-plus-jakarta)", "sans-serif"],
        "label-md": ["var(--font-plus-jakarta)", "sans-serif"],
        "display-hero": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-lead": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-sm": ["var(--font-plus-jakarta)", "sans-serif"],
        "display-hero-mobile": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-md": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-xl": ["var(--font-plus-jakarta)", "sans-serif"],
        sans: ["var(--font-plus-jakarta)", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-eyebrow": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-xl-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }],
        "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-lead": ["16px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "display-hero-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
